name: Publish

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*.*.*-beta.*'  # Beta versions, v1.0.0-beta.1, v2.1.0-beta.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build
      - run: npm publish --access public
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish --access public --tag beta
        if: github.event_name == 'push'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
